// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/sigillum/api/v1"
)

// SealStatusApplyConfiguration represents a declarative configuration of the SealStatus type for use
// with apply.
type SealStatusApplyConfiguration struct {
	Phase *apiv1.SealPhase `json:"phase,omitempty"`
	// ObservedGeneration is the spec generation the phase was computed from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Message explains a Failed phase.
	Message *string `json:"message,omitempty"`
}

// SealStatusApplyConfiguration constructs a declarative configuration of the SealStatus type for use with
// apply.
func SealStatus() *SealStatusApplyConfiguration {
	return &SealStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *SealStatusApplyConfiguration) WithPhase(value apiv1.SealPhase) *SealStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SealStatusApplyConfiguration) WithObservedGeneration(value int64) *SealStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *SealStatusApplyConfiguration) WithMessage(value string) *SealStatusApplyConfiguration {
	b.Message = &value
	return b
}
