// Code generated by controller-gen. DO NOT EDIT.

package v1

// SealSpecApplyConfiguration represents a declarative configuration of the SealSpec type for use
// with apply.
//
// SealSpec describes who may reach the sealed namespace.
type SealSpecApplyConfiguration struct {
	// AllowedNamespaces names the namespaces that may reach this one, on top of
	// the claim namespace the seal's own namespace is annotated with. Ignored
	// when AllowAllNamespaces is true.
	AllowedNamespaces []string `json:"allowedNamespaces,omitempty"`
	// AllowAllNamespaces allows access from every namespace in the cluster,
	// effectively disabling the NetworkPolicy. It overrides AllowedNamespaces
	// and the claim namespace. Traffic from outside the cluster stays blocked.
	AllowAllNamespaces *bool `json:"allowAllNamespaces,omitempty"`
}

// SealSpecApplyConfiguration constructs a declarative configuration of the SealSpec type for use with
// apply.
func SealSpec() *SealSpecApplyConfiguration {
	return &SealSpecApplyConfiguration{}
}

// WithAllowedNamespaces adds the given value to the AllowedNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedNamespaces field.
func (b *SealSpecApplyConfiguration) WithAllowedNamespaces(values ...string) *SealSpecApplyConfiguration {
	for i := range values {
		b.AllowedNamespaces = append(b.AllowedNamespaces, values[i])
	}
	return b
}

// WithAllowAllNamespaces sets the AllowAllNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowAllNamespaces field is set to the value of the last call.
func (b *SealSpecApplyConfiguration) WithAllowAllNamespaces(value bool) *SealSpecApplyConfiguration {
	b.AllowAllNamespaces = &value
	return b
}
