// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/helmetica-framework/sigillum/api/v1"
	apiv1 "github.com/helmetica-framework/sigillum/applyconfiguration/api/v1"
	internal "github.com/helmetica-framework/sigillum/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=seals.helmetica.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("Seal"):
		return &apiv1.SealApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SealSpec"):
		return &apiv1.SealSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("SealStatus"):
		return &apiv1.SealStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
