apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-admin-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - seals.helmetica.io
  resources:
  - seals
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups:
  - seals.helmetica.io
  resources:
  - seals/status
  verbs: [get]
