---
name: Check for Vulnerabilities

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  check-for-vulnerabilities:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'

      - name: Run govulncheck and save to file
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -format sarif ./... > govulncheck.sarif
        env:
          GOEXPERIMENT: jsonv2

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
